python main.py \
    --task cifar10_cnum16_dist2_skew0.6_seed0 \
    --model cnn \
    --algorithm mp_sv_fedavg \
    --num_rounds 2 \
    --num_epochs 1 \
    --learning_rate 0.01 \
    --lr_scheduler 0 \
    --learning_rate_decay 0.998 \
    --proportion 1 \
    --batch_size 10 \
    --eval_interval 1 \
    --gpu 1 \
    --num_threads_per_gpu 1 \
    # --num_partitions 2 \
    # --const_lambda \
    # --optimal_lambda \
    # --optimal_lambda_samples 300
    # --exact \