python main.py \
    --task mnist_cnum50_dist0_skew0_seed0 \
    --model mlp \
    --algorithm mp_fedavg \
    --num_rounds 450 \
    --num_epochs 10 \
    --learning_rate 0.01 \
    --lr_scheduler 0 \
    --learning_rate_decay 0.998 \
    --proportion 1 \
    --batch_size 10 \
    --eval_interval 1 \
    --gpu 1 \
    --num_threads_per_gpu 2