python main.py \
    --task fashion_mnist_cnum16_dist2_skew1.0_seed0 \
    --model lr \
    --algorithm mp_fedavg \
    --num_rounds 200 \
    --num_epochs 5 \
    --learning_rate 0.01 \
    --lr_scheduler 0 \
    --learning_rate_decay 0.998 \
    --proportion 1 \
    --batch_size 10 \
    --eval_interval 1 \
    --gpu 0 \
    --num_threads_per_gpu 2